// client/src/app/shared/components/header.component.tsx
import { useLocation, useNavigate } from "react-router-dom";

import Button from "./button.component";
import Logo from "./logo.component";

const Header = () => {
  const navigate = useNavigate();
  const { pathname } = useLocation();

  const getButtonVariant = (route: "/sign-in" | "/sign-up") => {
    return pathname === route ? "solid" : "outline";
  };

  return (
    <header className="absolute top-0 left-0 h-14 w-full px-4 lg:px-8 flex items-center justify-center shadow-xl">
      <div className="lg:max-w-7xl flex flex-grow items-center justify-between">
        <Logo />
        <div className="flex gap-2 lg:gap-4">
          <Button
            variant={getButtonVariant("/sign-in")}
            onClick={() => navigate("/sign-in")}
            size="m"
          >
            Sign In
          </Button>

          <Button
            variant={getButtonVariant("/sign-up")}
            onClick={() => navigate("/sign-up")}
            size="m"
          >
            Sign Up
          </Button>
        </div>
      </div>
    </header>
  );
};

export default Header;

// client/src/app/core/components/header/header.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';

import { SharedModule } from '../../../shared/shared.module';
import { LogoComponent } from '../logo/logo.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [SharedModule, LogoComponent, RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
})
export class HeaderComponent {
  constructor(private router: Router) {}

  getAuthButtonVariant(route: '/sign-in' | '/sign-up') {
    return this.router.url === route ? 'solid' : 'outline';
  }
}

<header
  class="h-14 w-full px-4 lg:px-8 flex items-center justify-center shadow"
>
  <div class="lg:max-w-7xl flex flex-grow items-center justify-between">
    <app-logo />
    <div class="flex gap-2 lg:gap-4">
      <app-button
        routerLink="/sign-in"
        [variant]="getAuthButtonVariant('/sign-in')"
        size="m"
        >Sign In</app-button
      >

      <app-button
        routerLink="/sign-up"
        [variant]="getAuthButtonVariant('/sign-up')"
        size="m"
        >Sign Up</app-button
      >
    </div>
  </div>
</header>
