// client/src/app/shared/components/button/button.component.ts
import { Component, Input } from '@angular/core';

const BUTTON_VARIANT = {
  solid: 'border-black bg-black text-white',
  outline: 'border-black text-black',
  ghost: 'border-transparent text-black',
};

const BUTTON_SIZE = {
  s: 'px-3 py-1 rounded-md text-caption',
  m: 'px-4 py-2 rounded-md text-body',
  l: 'px-4 py-3 rounded-lg text-body-lg',
};

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [],
  templateUrl: './button.component.html',
})
export class ButtonComponent {
  @Input() variant!: keyof typeof BUTTON_VARIANT;
  @Input() size!: keyof typeof BUTTON_SIZE;
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() disabled: boolean = false;

  getClasses(): string {
    return `${BUTTON_VARIANT[this.variant]} ${BUTTON_SIZE[this.size]}`;
  }
}

<button
  class="w-full border-2 text-center disabled:opacity-50 disabled:cursor-not-allowed"
  [class]="getClasses()"
  [type]="type"
  [disabled]="disabled"
>
  <ng-content />
</button>

// client/src/app/shared/components/button.component.tsx
import { FC, PropsWithChildren } from "react";
import classNames from "classnames";

const BUTTON_VARIANT = {
  solid: "border-black bg-black text-white",
  outline: "border-black text-black",
  ghost: "border-transparent text-black",
};

const BUTTON_SIZE = {
  s: "px-3 py-1 rounded-md text-caption",
  m: "px-4 py-2 rounded-md text-body",
  l: "px-4 py-3 rounded-lg text-body-lg",
};

type ButtonProps = PropsWithChildren<{
  variant: keyof typeof BUTTON_VARIANT;
  size: keyof typeof BUTTON_SIZE;
  onClick?: () => void;
  type?: "button" | "submit" | "reset";
  disabled?: boolean;
}>;

const Button: FC<ButtonProps> = ({
  variant,
  size,
  onClick,
  type = "button",
  disabled = false,
  children,
}) => {
  return (
    <button
      className={classNames(
        "border-2 text-center disabled:opacity-50 disabled:cursor-not-allowed",
        BUTTON_VARIANT[variant],
        BUTTON_SIZE[size],
      )}
      onClick={onClick}
      type={type}
      disabled={disabled}
    >
      {children}
    </button>
  );
};

export default Button;
