// client/src/app/shared/components/container/container.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-container',
  standalone: true,
  imports: [],
  templateUrl: './container.component.html',
})
export class ContainerComponent {}

<div class="h-container-height lg:max-w-7xl mx-auto px-4 lg:px-8 flex flex-col">
  <ng-content />
</div>

// client/src/app/shared/components/container.component.tsx
import { FC, PropsWithChildren } from "react";

type ContainerProps = PropsWithChildren;

const Container: FC<ContainerProps> = ({ children }) => {
  return (
    <div className="h-container lg:max-w-screen-2xl mx-auto py-2 px-4 lg:px-8 flex flex-col">
      {children}
    </div>
  );
};

export default Container;
