// client/src/app/shared/components/input/input.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-input',
  standalone: true,
  imports: [],
  templateUrl: './input.component.html',
})
export class InputComponent {
  @Input() label: string = '';
  @Input() hasError: boolean = false;
  @Input() hint: string = '';
}

<label class="flex flex-col">
  @if (label) {
    <span class="uppercase leading-tight tracking-tight">{{ label }}</span>
  }

  <input
    class="py-1 px-3 border-2 rounded-lg text-lg tracking-tight border-black text-black placeholder:text-primary-400 outline-none"
    [class.border-error]="hasError"
    placeholder="Enter something"
  />

  @if (hint) {
    <span class="tracking-tight" [class.text-error]="hasError">{{ hint }}</span>
  }
</label>

// client/src/app/shared/components/input.component.tsx
import { FC } from "react";
import { useFormContext } from "react-hook-form";
import classNames from "classnames";

type InputProps = {
  label?: string;
  placeholder?: string;
  error?: string;
  name?: string;
};

const Input: FC<InputProps> = ({ label, placeholder, error, name }) => {
  const { register } = useFormContext();

  return (
    <label className="flex flex-col">
      {label && <span className="text-caption uppercase">{label}</span>}

      <input
        className={classNames(
          "py-1 px-3 border-2 rounded-lg text-body border-black text-black placeholder:text-primary-400 outline-none",
          {
            "border-error": error,
          },
        )}
        placeholder={placeholder}
        {...(name ? register(name) : {})}
      />

      {error && (
        <div className="text-caption text-error">
          <span>{error}</span>
        </div>
      )}
    </label>
  );
};

export default Input;
