// client/src/app/features/auth/components/auth-form/auth-form.component.ts
import { Component, Input } from '@angular/core';

import { SharedModule } from '../../../../shared/shared.module';

@Component({
  selector: 'app-auth-form',
  standalone: true,
  imports: [SharedModule],
  templateUrl: './auth-form.component.html',
})
export class AuthFormComponent {
  @Input() title!: string;
}

<form class="h-container-height lg:w-1/3 flex flex-col mx-auto justify-center">
  <h2 class="self-center text-header-3 lg:text-header-2">{{ title }}</h2>
  <div class="mb-2">
    <ng-content />
  </div>
  <app-button variant="solid" size="m" type="submit">Submit</app-button>
</form>

// client/src/app/features/auth/components/auth-form.component.tsx
import { FC, PropsWithChildren } from "react";

import Button from "@shared/components/button.component";

type AuthFormProps = PropsWithChildren<{
  title: string;
  onSubmit: () => void;
}>;

const AuthForm: FC<AuthFormProps> = ({ title, onSubmit, children }) => {
  return (
    <form
      className="h-container w-full lg:w-1/3 mx-auto flex flex-col justify-center gap-2"
      onSubmit={onSubmit}
    >
      <h2 className="self-center text-header-2 lg:text-header-1">{title}</h2>
      <div className="flex flex-col gap-1">{children}</div>
      <Button variant="solid" size="m" type="submit">
        Submit
      </Button>
    </form>
  );
};

export default AuthForm;
